# Generated by Django 5.2.8 on 2025-11-24 13:25

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="image",
            field=models.ImageField(null=True, upload_to=airport.models.upload_images),
        ),
    ]
